stages:
  - build
  - test
  - pack
  
image: mcr.microsoft.com/dotnet/core/sdk:3.1
  
build:
  stage: build
  tags:
    - docker
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    when: on_success
    expire_in: 1 month
    paths:
      - "**/bin"
      - "**/obj"
  script:
    - "dotnet build src/HEAL.Bricks"
    - "dotnet build src/HEAL.Bricks.Tests"
    - "dotnet build src/HEAL.Bricks.XTests"
    - "dotnet build-server shutdown"

test:
  stage: test
  tags:
    - docker
  dependencies:
    - build
  artifacts:
    reports:
      cobertura: "**/coverage.cobertura.xml"
  script:
#    - "dotnet test src/HEAL.Bricks.Tests  --no-build"
    - "dotnet test src/HEAL.Bricks.XTests --no-build --collect:\"XPlat Code Coverage\""

pack:
  stage: pack
  tags:
    - docker
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 month
    paths:
      - nupkgs/*
  script:
    - "dotnet pack src/HEAL.Bricks.PluginTypes -c Release --include-symbols --output nupkgs"
    - "dotnet pack src/HEAL.Bricks -c Release --include-symbols --output nupkgs"
    - "dotnet build-server shutdown"
