stages:
  - build
  - test
  - pack
  
variables:
  publish_debug_path: "bin/Debug/netcoreapp3.0/publish"
  publish_release_path: "bin/Release/netcoreapp3.0/publish"
  deploy_staging_path: "/home/gitlab-runner/$project"
  deploy_production_path: "/home/gitlab-runner/dynstack2020"

image: mcr.microsoft.com/dotnet/core/sdk:3.1
  
build:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    when: on_success
    expire_in: 1 month
    paths:
      - "**/bin"
  script:
    - "dotnet build src/HEAL.Bricks.PluginTypes"
    - "dotnet build src/HEAL.Bricks"
    - "dotnet build src/HEAL.Bricks.Tests"
    - "dotnet build src/HEAL.Bricks.XTests"
    - "dotnet build-server shutdown"

test:
  stage: test
  dependencies:
    - build
  script:
    - "dotnet test src/HEAL.Bricks.Tests"
    - "dotnet test src/HEAL.Bricks.XTests"

pack:
  stage: pack
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 month
    paths:
      - nupkgs/*
  script:
    - "dotnet build src/HEAL.Bricks.PluginTypes -c Release"
    - "dotnet pack src/HEAL.Bricks.PluginTypes -c Release --include-symbols --output nupkgs"
    - "dotnet build src/HEAL.Bricks -c Release"
    - "dotnet pack src/HEAL.Bricks -c Release --include-symbols --output nupkgs"
    - "dotnet build-server shutdown"
